//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PromotionRuleModel.java
//  @ Date : 2014/2/20
//  @ Author : 
//
//




/** */
public class PromotionRuleModel
{
}
