//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SystemModel.java
//  @ Date : 2014/2/20
//  @ Author : 
//
//




/** */
public class SystemModel
{
    /** */
    public void getConfig()
    {
    
    }
    
    /** */
    public void setConfig()
    {
    
    }
}
