TRUNCATE TABLE tp_account;
TRUNCATE TABLE tp_account_apply;
TRUNCATE TABLE tp_login_log;
TRUNCATE TABLE tp_logs;
TRUNCATE TABLE tp_message;
TRUNCATE TABLE tp_user_suggest;
TRUNCATE TABLE tp_verify_code;
TRUNCATE TABLE tp_bet_log;
TRUNCATE TABLE tp_bet_auto;
TRUNCATE TABLE tp_bet_mode;
TRUNCATE TABLE tp_daily_bet;
TRUNCATE TABLE tp_daily_win;
TRUNCATE TABLE tp_game_log;
TRUNCATE TABLE tp_game_result;
TRUNCATE TABLE tp_rank_list;
TRUNCATE TABLE tp_red_packet;
TRUNCATE TABLE tp_red_packet_log;
TRUNCATE TABLE tp_return_log;
TRUNCATE TABLE tp_user_gift;
TRUNCATE TABLE tp_user_gift_password;
DELETE FROM tp_users WHERE role_type = 3;
DELETE FROM tp_users WHERE role_type = 4;
